image: hpclib/hiepacs

stages:
  - build
  - test
  - analysis
  - doc

before_script:
  - git submodule update --init --recursive
  - source .gitlab-ci-env.sh $SIMU
  - mkdir -p build

.build_script_template: &build_script
  stage: build
  script:
    - echo BUILD_OPTIONS $BUILD_OPTIONS
    - echo VERSION $VERSION
    - (cd build &&
       cmake -C ../cmake_modules/gitlab-ci-initial-cache.cmake ..
             $BUILD_OPTIONS &&
        ctest --no-compress-output -V -j 5
             -D ExperimentalBuild
             -D ExperimentalSubmit
             | tee ../chameleon_${VERSION}.log)
    - (cd build &&
       make install | tee -a ../chameleon_${VERSION}.log &&
       rm install/ -r)

.test_script_template: &test_script
  stage: test
  script:
    - echo TESTS_RESTRICTION $TESTS_RESTRICTION
    - echo VERSION $VERSION
    - (cd build &&
       eval "ctest --no-compress-output -V
             $TESTS_RESTRICTION
             -D ExperimentalTest
             -D ExperimentalCoverage
             -D ExperimentalSubmit
             | tee -a ../chameleon_${VERSION}.log")
    - lcov --directory build --capture --output-file ./chameleon_${VERSION}.lcov

build_starpu:
  <<: *build_script
  artifacts:
    name: build_starpu
    expire_in: 48 hours
    paths:
      - build
      - chameleon_starpu.log
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MPI=ON"
    VERSION: starpu

test_starpu_branches:
  <<: *test_script
  variables:
    TESTS_RESTRICTION: "-R \"test_shm_|test_mpi_\""
    VERSION: starpu
  dependencies:
    - build_starpu
  artifacts:
    name: test_starpu
    expire_in: 48 hours
    paths:
      - build
      - chameleon_starpu.log
      - chameleon_starpu.lcov
  only:
    - branches
  except:
    - master

test_starpu_master:
  <<: *test_script
  variables:
    TESTS_RESTRICTION: "-R \"test_shm_|test_mpi_\""
    VERSION: starpu
  dependencies:
    - build_starpu
  artifacts:
    name: test_starpu
    expire_in: 48 hours
    paths:
      - build
      - chameleon_starpu.log
      - chameleon_starpu.lcov
  only:
    - master@solverstack/chameleon

sonar:
  stage: analysis
  dependencies:
    - test_starpu_branches
  artifacts:
    name: chameleon_analysis
    expire_in: 1 week
    paths:
      - chameleon_build.log
      - chameleon_coverage.xml
      - chameleon_cppcheck.xml
      - chameleon_rats.xml
      - sonar.log
  script:
    - cat *.log > chameleon_build.log
    - lcov -a $PWD/chameleon_starpu.lcov
           -o $PWD/chameleon.lcov
    - lcov_cobertura.py chameleon.lcov --output chameleon_coverage.xml
    - ./tools/analysis.sh

doc:
  stage: doc
  artifacts:
    name: chameleon_doc
    expire_in: 1 week
    paths:
      - build/doc/doxygen
      - build/doc/orgmode
  script:
    - cd build
    - cmake .. -DCHAMELEON_ENABLE_DOC=ON
    - make doc -j5
  only:
    - master@solverstack/chameleon
