---
build_hmat:
  extends: .build_script_template
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_USE_CUDA=OFF -DCHAMELEON_USE_MPI=ON -DCHAMELEON_USE_HMAT=ON"
    VERSION: hmat

build_openmp:
  extends: .build_script_template
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED=OPENMP"
    VERSION: openmp

build_parsec:
  extends: .build_script_template
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED=PARSEC"
    VERSION: parsec

build_quark:
  extends: .build_script_template
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_SCHED=QUARK"
    VERSION: quark

build_starpu:
  extends: .build_script_template
  variables:
    BUILD_OPTIONS: "-DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MPI=ON"
    VERSION: starpu

build_starpu_simgrid:
  extends: .build_script_template
  variables:
    SIMU: simu
    BUILD_OPTIONS: "-DCHAMELEON_SIMULATION=ON -DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MPI=OFF"
    VERSION: starpu_simgrid

build_starpu_macosx:
  extends: .only-master
  stage: build
  tags: ['macosx']
  variables:
    VERSION: starpu
  script:
    - tools/build_macosx.sh
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    expire_in: 2 days
    untracked: true
    when: always
